name: Hello

on:
  push:
    branches:
      - main

jobs:
  # this is job 1
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello to users
        run: echo "Hello Raj"
      - name: Say hello to username
        run: echo "Hello $USER"
  
  # this is job 2
  check_version:
      runs-on: ubuntu-latest
      steps:
        - name: check python and docker version
          run: python --version &&  docker --version

    
