---
name: Hello
on:
  push:
    branches:
      - main
jobs: null
greet: null
runs-on: ubuntu-latest
steps:
  - name: Say hello to users
    run: echo 'Hello Avnish'
  - name: Say hello to username
    run: echo "Hello $USER"
